### ISSUE TITLE
Button to delete currently selected node/segment?

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NetworkDetective#1]
Would be useful for removing ghost nodes/segments, particularly those discussed in https://github.com/CitiesSkylinesMods/TMPE/issues/825#issuecomment-614321900

Button could appear on the segment/node entries in the UI (or whatever is easiest)?

![image](https://user-images.githubusercontent.com/1386719/88446179-b25d7a00-ce1f-11ea-9dda-e4e559b8aca8.png)

This would make the tool useful for users who want to remove dead nodes/segments but don't want to use Mod Tools (MT can cause issues for some users).

**Comment by kianzarrin** [comment]
done
