### ISSUE TITLE
`IndexOutOfRangeException` in GoToPanel

### ISSUE THREAD

**Issue by krzychu124** [kianzarrin/NetworkDetective#3]
https://github.com/kianzarrin/NetworkDetective/blob/0f897877a4917583bb9821a2f9df0be7b5f6edf1/NetworkDetective/UI/GoToPanel/GoToPanel.cs#L200-L201

First line throws an exception if you type in a **valid** lane or segment index (value higher than node limit)

**Comment by kianzarrin** [comment]
fix uploaded to WS at version 1.0.5
