### ISSUE TITLE
API for mods to open ND

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NetworkDetective#4]
Would it be possible to get an API for other mods to easily open ND focussed on a specific node, segment, or lane?

Ideally just by passing an `InstanceID`.

I want to rework TMPE label overlays so that when clicked they open ND (if it's subscribed & enabled) = far more useful than a spam of overlapping text labels.

Additionally: Same thing for Mod Tools.

And for both, a method/getter that determines if the mod is available (eg. if ND isn't available I'll fall back to MT).

**Comment by originalfoo** [comment]
Bonus round: Button in ND that will open the node/segment/lane in MT

**Comment by kianzarrin** [comment]
the focus of ND is to help understanding directions (start/end head/tail invert LHT forward/backward ...)
It does not display traffic data that is displayed in TMPE.
also its a tool not a window so activating it will switch of TMPE tool (unless if I change the code).

modtools scene editor allows to modify data. ND cannot be a replacement for mod tools.
